name: ClassicPress Directory Coding Standard checks.
on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: CPCS
    runs-on: ubuntu-latest
    steps:
      # Update to v6 to support Node 24
      - uses: actions/checkout@v6

      # Explicitly set up Node 24 to avoid environment mismatch
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: CPCS get rules
        run: |
          wget -O phpcs.xml https://raw.githubusercontent.com/ClassicPress/ClassicPress-Coding-Standards/main/phpcs.xml
          sed -i '/^\t.*/a\    <file>.</file> ' phpcs.xml
          sed -i '/MY_DOMAIN/ s//alt-tag-healer/' phpcs.xml
          mv phpcs.xml phpcs.xml.dist

      - name: CPCS checks
        # Verify if there is a version newer than @stable (e.g., @v3)
        uses: 10up/wpcs-action@stable 
        with:
          use_local_config: 'true'
          enable_warnings: 'true'
          extra_args: '--report-json=./phpcs.json'

      - name: Update summary
        run: |
          npm i -g github:10up/phpcs-json-to-md
          phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
          cat phpcs.md >> $GITHUB_STEP_SUMMARY
        if: always()