name: Generate Clean Release Zip

on:
  push:
    tags:
      - 'v*' # Triggers when you push a tag like v1.2.0

jobs:
  build:
    name: Create Release and Upload Zip
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to upload assets to a release
    steps:
      - name: Checkout code release
        uses: actions/checkout@v6

      - name: Build Plugin Zip
        id: build_zip
        uses: 10up/action-wordpress-plugin-build-zip@stable

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: alt-tag-healer.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}